apiVersion: apps/v1
kind: Deployment
metadata:
  name: smoke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smokeclassifier
  template:
    metadata:
      labels:
        app: smokeclassifier
    spec:
      containers:
      - name: smokeclassifier-app
        image: us-west4-docker.pkg.dev/affable-beach-268518/smoker/smoker
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"